name: IngameLog
main: eu.jailbreaker.log.IngameLog
version: 1.0
api-version: 1.13
load: POSTWORLD
website: https://jailbreaker.eu
author: JailBreaker
commands:
  log:
    aliases:
      - ingamelog
description: Simple plugin to view the current server logs
